language: php

php:
  - 5.3
  - 5.4

env:
    - SYMFONY_VERSION=2.0.*
    - SYMFONY_VERSION=2.1.*
    - SYMFONY_VERSION=dev-master

before_script:
    - curl -s http://getcomposer.org/installer | php
    - sh vendors
